# Use Ubuntu 14.04 Trusty for GCC 4.8
dist: trusty
sudo: required
language: cpp

branches:
  only:
  - master

matrix:
  include:
  - compiler: clang

before_install:
- export CC=${TRAVIS_CC:-$CC} && $CC --version
- export CXX=${TRAVIS_CXX:-$CXX} && $CXX --version
- sudo apt-get update -qq
- sudo apt-get install -y libxml2-dev

script:
- ./install.sh
- . hclib-install/bin/hclib_setup_env.sh
- curl -k https://gist.githubusercontent.com/DaoWen/fcbdd8b2f95678c3098776b174f1d7c8/raw/ > debug.bash
- pushd test/c/   && ./test_all.sh && popd
- pushd test/cpp/ && ./test_all.sh && popd
