# Use Ubuntu 14.04 Trusty for GCC 4.8
dist: trusty
sudo: required
language: cpp

branches:
  only:
  - master

matrix:
  include:
  - env: TRAVIS_CC=clang-3.4 TRAVIS_CXX=clang++-3.4
    addons:
      apt:
        packages:
          - clang-3.4
        sources:
          - llvm-toolchain-trusty-3.4
  include:
  - env: TRAVIS_CC=clang-3.5 TRAVIS_CXX=clang++-3.5
    addons:
      apt:
        packages:
          - clang-3.5
        sources:
          - llvm-toolchain-trusty-3.5
  - env: TRAVIS_CC=clang-3.6 TRAVIS_CXX=clang++-3.6
    addons:
      apt:
        packages:
          - clang-3.6
        sources:
          - llvm-toolchain-trusty-3.6
  - env: TRAVIS_CC=clang-3.7 TRAVIS_CXX=clang++-3.7
    addons:
      apt:
        packages:
          - clang-3.7
        sources:
          - llvm-toolchain-trusty-3.7

before_install:
- export CC=${TRAVIS_CC:-$CC} && $CC --version
- export CXX=${TRAVIS_CXX:-$CXX} && $CXX --version
- sudo apt-get update -qq
- sudo apt-get install gdb
- sudo apt-get install -y libxml2-dev
- sudo bash -c 'echo core > /proc/sys/kernel/core_pattern'

script:
- ./install.sh
- . hclib-install/bin/hclib_setup_env.sh
- curl -k https://gist.githubusercontent.com/DaoWen/fcbdd8b2f95678c3098776b174f1d7c8/raw/ > debug.bash
- ulimit -c unlimited
- pushd test/c/   && ./test_all.sh && popd
- pushd test/cpp/ && ./test_all.sh && popd
